import { readFileSync, writeFileSync } from "node:fs";
import { PROJECTS } from "../src/data/profile";

const SKILL_CATEGORIES: Record<string, string[]> = {
	Languages: ["TypeScript", "JavaScript", "Python", "Go"],
	"AI / ML": ["PyTorch", "RL (PPO)", "Hugging Face", "LangChain", "MCP"],
	Frontend: [
		"React",
		"Next.js",
		"Tailwind CSS",
		"Socket.io",
		"Framer Motion",
	],
	Backend: ["NestJS", "Node.js", "Bun", "Hono", "Express", "Go", "FastAPI", "Django", "PayloadCMS", "BullMQ"],
	Databases: ["PostgreSQL", "MongoDB", "Redis"],
	DevOps: ["Docker", "Linux", "Nginx", "CI/CD", "Coolify"],
	Cloud: ["AWS"],
	Testing: ["Jest", "React Testing Library"],
};



function generate(): string {
	const skillRows = Object.entries(SKILL_CATEGORIES)
		.map(([cat, skills]) => `| **${cat}** | ${skills.join(", ")} |`)
		.join("\n");

	const projectBullets = PROJECTS
		.map((p) => p.url
			? `- [**${p.name}**](${p.url}): ${p.description}`
			: `- **${p.name}**: ${p.description}`)
		.join("\n");

	const lines = [
		`<div align="center">`,
		``,
		`  # 👋 Hi, I'm Najish Mahmud`,
		``,
		`  **Full Stack Engineer**`,
		``,
		`  [njayman.com](https://njayman.com) • [LinkedIn](https://linkedin.com/in/najishmahmud/) • [Codeberg](https://codeberg.org/njayman)`,
		``,
		`</div>`,
		``,
		`---`,
		``,
		`## 🛠️ Skills`,
		``,
		`| Category | Technologies |`,
		`|----------|-------------|`,
		skillRows,
		``,
		`---`,
		``,
		`## 📌 Featured Projects`,
		``,
		projectBullets,
		``,
		`---`,
		``,
		`## 📊 GitHub Stats`,
		``,
		`<div align="center">`,
		``,
		`  <img src="./profile/top-langs.svg" alt="Top Languages" />`,
		``,
		`  <br>`,
		``,
		`  <img src="./profile/stats.svg" alt="GitHub Stats" />`,
		``,
		`</div>`,
		``,
		`---`,
		``,
		`*README auto-generated by [scripts/generate-readme.ts](scripts/generate-readme.ts) on push.*`,
	];

	return lines.join("\n");
}

function main() {
	const readmePath = new URL("../README.md", import.meta.url).pathname;
	const generated = generate();
	const existing = readFileSync(readmePath, "utf-8");

	if (existing === generated) {
		console.log("README.md is up to date.");
		return;
	}

	writeFileSync(readmePath, generated);
	console.log("README.md updated.");
}

main();
