import { readFileSync, writeFileSync } from "node:fs";

const SKILL_CATEGORIES: Record<string, string[]> = {
	Languages: ["TypeScript", "JavaScript", "Python", "Go"],
	Frontend: [
		"React",
		"Next.js",
		"Tailwind CSS",
		"Socket.io",
		"Framer Motion",
	],
	Backend: ["NestJS", "Node.js", "Express", "Go", "FastAPI", "Django", "PayloadCMS"],
	Databases: ["PostgreSQL", "Redis", "BullMQ"],
	DevOps: ["Docker", "Linux", "Nginx", "CI/CD", "Coolify"],
	Cloud: ["Azure", "AWS"],
	Testing: ["Jest", "React Testing Library"],
};

const REPO_OWNER = "njayman";

const PROJECTS: { name: string; desc: string; url?: string }[] = [
	{ name: "proz", desc: "Cross-platform CLI + TUI project launcher built with Go, Bubbletea and Cobra. Fuzzy-find and jump between projects from any terminal.", url: `https://github.com/${REPO_OWNER}/proz` },
	{ name: "raylibgame", desc: "2D boss-fight game built with Go and raylib — state-machine AI, collision detection, HUD, and health-bar systems.", url: `https://github.com/${REPO_OWNER}/raylibgame` },
	{ name: "NoticeBee", desc: "Realtime notice platform built with Socket.io and React — admin dashboard, kiosk display, multipart upload, layout management. Adopted by 100+ government colleges under CEDP." },
	{ name: "Medibee", desc: "MERN stack subscription platform serving curated medical video content via Vimeo. Admin panel, student dashboards, and 1,000+ active subscribers." },
];


function generate(): string {
	const skillRows = Object.entries(SKILL_CATEGORIES)
		.map(([cat, skills]) => `| **${cat}** | ${skills.join(", ")} |`)
		.join("\n");

	const projectBullets = PROJECTS
		.map((p) => p.url
			? `- [**${p.name}**](${p.url}) — ${p.desc}`
			: `- **${p.name}** — ${p.desc}`)
		.join("\n");

	const lines = [
		`<div align="center">`,
		``,
		`  # 👋 Hi, I'm Najish Mahmud`,
		``,
		`  **Full Stack Engineer**`,
		``,
		`  [njayman.com](https://njayman.com) • [LinkedIn](https://linkedin.com/in/najishmahmud/) • [Codeberg](https://codeberg.org/njayman)`,
		``,
		`</div>`,
		``,
		`---`,
		``,
		`## 🛠️ Skills`,
		``,
		`| Category | Technologies |`,
		`|----------|-------------|`,
		skillRows,
		``,
		`---`,
		``,
		`## 📌 Featured Projects`,
		``,
		projectBullets,
		``,
		`---`,
		``,
		`## 📊 GitHub Stats`,
		``,
		`<div align="center">`,
		``,
		`  <img src="./profile/top-langs.svg" alt="Top Languages" />`,
		``,
		`  <br>`,
		``,
		`  <img src="./profile/stats.svg" alt="GitHub Stats" />`,
		``,
		`</div>`,
		``,
		`---`,
		``,
		`*README auto-generated by [scripts/generate-readme.ts](scripts/generate-readme.ts) on push.*`,
	];

	return lines.join("\n");
}

function main() {
	const readmePath = new URL("../README.md", import.meta.url).pathname;
	const generated = generate();
	const existing = readFileSync(readmePath, "utf-8");

	if (existing === generated) {
		console.log("README.md is up to date.");
		return;
	}

	writeFileSync(readmePath, generated);
	console.log("README.md updated.");
}

main();
